### ISSUE TITLE
ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by ali-tafakkori** [xtrinch/sx127x-node-driver#9]
(node:2612) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (6)
    at Object.writeFileSync (fs.js:1517:5)
    at exportGpio (/root/project/node_modules/sx127x-driver/node_modules/onoff/onoff.js:18:8)
    at new Gpio (/root/project/node_modules/sx127x-driver/node_modules/onoff/onoff.js:172:36)
    at SX127x.open (/root/project/node_modules/sx127x-driver/lib/sx127x.js:110:20)
    at run (/root/project/lora.js:15:22)
    at Object.<anonymous> (/root/project/lora.js:21:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2612) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
                                                  
```
const SX127x = require('sx127x-driver');

const sx127x = new SX127x({
    frequency: 433E6,
    dio0Pin: 6,
    resetPin: 13,
    spreadingFactor: 7,
    signalBandwidth: 125E3,
    codingRate: 4 / 5,
    preambleLength: 10,
    txPower: 20,
});

const run = async () => {
        await sx127x.open();
        await sx127x.write(Buffer.from("This is a test"));
        console.log("successfully sent");
        await sx127x.close();
};

run().then(r => {});
```

```
node -v
v14.17.4
```
```
npm -v
7.20.3
```

**Comment by ali-tafakkori** [comment]
I fix it by replace 6 to "6" and 13 to "13".
